# Generated by Django 6.1 on 2026-08-25 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=20)),
                ('from_city', models.CharField(choices=[('Lviv', 'Lviv'), ('Zolochiv', 'Zolochiv'), ('Ternopil', 'Ternopil'), ('Kraków', 'Kraków'), ('Wrocław', 'Wrocław'), ('Zielona Góra', 'Zielona Góra'), ('Świebodzin', 'Świebodzin'), ('Słubice', 'Słubice'), ('Kostrzyn nad Odrą', 'Kostrzyn nad Odrą'), ('Berlin', 'Berlin')], max_length=60)),
                ('to_city', models.CharField(choices=[('Lviv', 'Lviv'), ('Zolochiv', 'Zolochiv'), ('Ternopil', 'Ternopil'), ('Kraków', 'Kraków'), ('Wrocław', 'Wrocław'), ('Zielona Góra', 'Zielona Góra'), ('Świebodzin', 'Świebodzin'), ('Słubice', 'Słubice'), ('Kostrzyn nad Odrą', 'Kostrzyn nad Odrą'), ('Berlin', 'Berlin')], max_length=60)),
                ('departure_date', models.DateField()),
                ('seat_number', models.PositiveIntegerField(default=1)),
                ('baggage', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['departure_date', 'seat_number'],
            },
        ),
    ]
