# Generated by Django 6.0.4 on 2026-08-30 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportation_APP', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['departure_date', 'bus_number', 'seat_number']},
        ),
        migrations.AddField(
            model_name='booking',
            name='bus_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=20)),
                ('from_city', models.CharField(choices=[('Lviv', 'Lviv'), ('Zolochiv', 'Zolochiv'), ('Ternopil', 'Ternopil'), ('Kraków', 'Kraków'), ('Wrocław', 'Wrocław'), ('Zielona Góra', 'Zielona Góra'), ('Świebodzin', 'Świebodzin'), ('Słubice', 'Słubice'), ('Kostrzyn nad Odrą', 'Kostrzyn nad Odrą'), ('Berlin', 'Berlin')], max_length=60)),
                ('to_city', models.CharField(choices=[('Lviv', 'Lviv'), ('Zolochiv', 'Zolochiv'), ('Ternopil', 'Ternopil'), ('Kraków', 'Kraków'), ('Wrocław', 'Wrocław'), ('Zielona Góra', 'Zielona Góra'), ('Świebodzin', 'Świebodzin'), ('Słubice', 'Słubice'), ('Kostrzyn nad Odrą', 'Kostrzyn nad Odrą'), ('Berlin', 'Berlin')], max_length=60)),
                ('departure_date', models.DateField()),
                ('post_size', models.CharField(choices=[('велика', 'Велика'), ('середня', 'Середня'), ('мала', 'Мала')], max_length=20)),
                ('comments', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['departure_date'],
            },
        ),
    ]
