# Generated by Django 6.0.4 on 2026-08-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportation_APP', '0002_alter_booking_options_booking_bus_number_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['departure_date', 'bus_number']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_size',
        ),
        migrations.AddField(
            model_name='post',
            name='bus_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
