# Generated by Django 6.0.4 on 2026-09-01 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportation_APP', '0003_alter_post_options_remove_post_post_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('outbound', 'Рейси в напрямку'), ('return', 'Рейси повернення')], default='outbound', max_length=20)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='Transportation_APP.busgroup')),
            ],
            options={
                'ordering': ['group__kind', 'number'],
            },
        ),
    ]
