# Generated by Django 6.0.4 on 2026-09-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportation_APP', '0004_busgroup_bus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['direction', 'number']},
        ),
        migrations.RemoveField(
            model_name='bus',
            name='group',
        ),
        migrations.AddField(
            model_name='bus',
            name='direction',
            field=models.CharField(choices=[('outbound', 'Рейси в напрямку'), ('return', 'Рейси повернення')], default='outbound', max_length=20),
        ),
        migrations.AddField(
            model_name='bus',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
